#spring.profiles.active=local
spring:
  application:
    name: payment-execution-service
  profiles:
    active:
      - prod
  webflux:
    base-path: /api/payment-execution
  config:
    import:
      - 'classpath:kafka.yml'

  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:paymentexecution}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  liquibase:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DATABASE_NAME:paymentexecution}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    changeLog: "classpath:db/changelog/changelog-main.xml"

server:
  port: ${APP_PORT:8080}

springdoc:
  swagger-ui:
    path: /docs/swagger-ui
  api-docs:
    path: /docs/api-docs

redis:
  paymentExecution:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    ioThreadPoolSize: 4
    connectionTimeout: 10000
    readTimeout: 1500
    password: ${REDIS_PASSWORD:}
    sslEnabled: ${REDIS_SSL:false}

idempotentFilter:
  #  default PUT POST DELETE
  redis:
    hostname: ${REDIS_HOST:-localhost}
    port: ${REDIS_PORT:-6379}
    password: ${REDIS_PASSWORD:-}
    sslEnabled: ${REDIS_SSL:-false}
#    default 1h
#    ttlInSecond: 3600

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:8081}
  endpoints:
    web:
      base-path: /
      exposure:
        include:
          - prometheus
          - health
          - metrics
      path-mapping:
        health: /actuator/health
        prometheus: /actuator/prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
      show-components: always
  metrics:
    distribution:
      percentiles-histogram:
        "http.server.requests": true
      percentiles:
        "http.server.requests": 0.5, 0.90, 0.95, 0.99

kafka:
  securityProtocol: ${THOUGHT_MACHINE_KAFKA_SECURITY_PROTOCOL}
  sslProtocol: ${THOUGHT_MACHINE_KAFKA_SSL_PROTOCOL:TLSv1.2}
  sslEndpointIdentificationAlgorithmConfig: ${THOUGHT_MACHINE_SSL_ENDPOINT_ALGORITHM:https}
  saslUsername: ${THOUGHT_MACHINE_KAFKA_SASL_USERNAME}
  saslPassword: ${THOUGHT_MACHINE_KAFKA_SASL_PASSWORD}
  saslMechanisms: ${THOUGHT_MACHINE_KAFKA_SASL_MECHANISMS:SCRAM-SHA-512}
  groupId: payment-execution-service
  thoughtMachine:
    server: ${THOUGHT_MACHINE_KAFKA_SERVERS:localhost:9092}
    groupId: ${KAFKA_TM_CONSUMER_GROUP_ID:card-payment-execution-consumer-local-test}
    producers:


      lowPriorityTopic: ${LOW_PRIORITY_TM_PRODUCER_TOPIC:vault.core.postings.requests.low_priority.v1}
      highPriorityTopic: ${HIGH_PRIORITY_TM_PRODUCER_TOPIC:vault.core.postings.requests.v1}
    consumers:

  settlementService:
    server: ${KAFKA_PLAINTEXT_SERVERS:localhost:9092}
    groupId: ${KAFKA_TM_CONSUMER_GROUP_ID:card-payment-execution-consumer-local}
    consumers:

    producers:
      cardSettlementDlqTopic: ${SETTLEMENT_TRANSACTION_EXECUTION_DLQ_TOPIC:sit.settlement_service.execution_event.dlq}

cbsPollingConfig:
  postingTimeout: ${CBS_REDIS_POSTING_TIMEOUT:5000} #ms
  pollingInterval: ${CBS_REDIS_POLLING_INTERVAL:150} #ms
  pollingTimeout: ${CBS_REDIS_POLLING_TIMEOUT:12000} #ms

internalAccount:
  expiredInDays: ${INTERNAL_ACCOUNT_EXPIRED_DAY:7} #days

effectiveTimestamp:
  enabled: ${EFFECTIVE_TIMESTAMP_ENABLED:false}

local:


blacklist:
  additional-data: ${BLACKLIST_ADDITIONAL_DATA:originating_account_id}
