"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const appointment_controller_1 = require("../controllers/appointment.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
const appointmentController = new appointment_controller_1.AppointmentController();
router.get('/', auth_middleware_1.authMiddleware, appointmentController.getUserAppointments);
router.post('/', auth_middleware_1.authMiddleware, appointmentController.createAppointment);
router.put('/:id/cancel', auth_middleware_1.authMiddleware, appointmentController.cancelAppointment);
router.get('/:id', auth_middleware_1.authMiddleware, appointmentController.getAppointmentById);
router.put('/:id', auth_middleware_1.authMiddleware, appointmentController.updateAppointment);
exports.default = router;
