apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
data:
  sonar.properties: |
    sonar.jdbc.username=sonar
    sonar.jdbc.password=sonar
    sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
        env:
        - name: SONARQUBE_JDBC_USERNAME
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: sonar.jdbc.username
        - name: SONARQUBE_JDBC_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: sonar.jdbc.password
        - name: SONARQUBE_JDBC_URL
          valueFrom:
            configMapKeyRef:
              name: sonarqube-config
              key: sonar.jdbc.url
        volumeMounts:
        - name: sonarqube-config-volume
          mountPath: /opt/sonarqube/conf
      volumes:
      - name: sonarqube-config-volume
        configMap:
          name: sonarqube-config

---

apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer