version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test