package com.example.clean_architect.infastructure.persistence.jpa.mappers;

import com.example.clean_architect.domain.entities.User;
import com.example.clean_architect.infastructure.persistence.jpa.entities.UserEntity;
import com.example.clean_architect.infastructure.persistence.mappers.UserMapper;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class UserMapperTest {
    private final UserMapper userMapper = new UserMapper();

    @Test
    void toJpaEntity() {
        User user = new User("name", "email");
        UserEntity userJpaEntity = userMapper.toEntity(user);
        assertNull(userJpaEntity.getId()); //Check id is not being mapped, as is generated by the database
        assertEquals(user.getName(), userJpaEntity.getName());
        assertEquals(user.getEmail(), userJpaEntity.getEmail());
    }
}
