spring:
  # profiles: local
  config:
    activate:
      on-profile: local

kafkaui:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      zookeeper: localhost:2181
      schemaRegistry: http://localhost:8081
      ksqldbServer: http://localhost:8088
      connect:
        - name: local-connect
          address: http://localhost:8083
      properties:
        consumer:
          auto.offset.reset: earliest
        producer:
          key.serializer: org.apache.kafka.common.serialization.StringSerializer
          value.serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.provectus: DEBUG
    reactor: DEBUG
    org.springframework.http.client.reactive: DEBUG