spring:
  application:
    name: ewallet-lab-user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:ewallet_user}
    username: ${DB_USER:ewallet_user}
    password: ${DB_PASSWORD:ewallet_user}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8090

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
